import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * Prefix on every ZELLÉ ingestion key.
 *
 * Two reasons for it. It makes a leaked key recognisable in a log or a paste,
 * and secret-scanning tools (GitHub's included) can be taught to match the
 * pattern and alert you.
 */
export const API_KEY_PREFIX = "zlk_";

/** 32 bytes = 256 bits of entropy. See hashApiKey() for why that number matters. */
const KEY_BYTES = 32;

/**
 * Hash an API key for storage and lookup.
 *
 * Lowercase hex SHA-256 over the UTF-8 bytes of the raw key. This MUST stay
 * byte-for-byte identical to the SQL side, which computes:
 *
 *     encode(sha256(convert_to(raw, 'UTF8')), 'hex')
 *
 * If the two ever diverge, every request 401s and the cause is not obvious.
 *
 * WHY NOT BCRYPT / ARGON2
 * Those exist because human passwords are low entropy — 'summer2024' is
 * guessable, so the hash is made deliberately slow to make guessing expensive.
 * They also salt with a random value per password, which means you can only
 * VERIFY a hash you already located by username; you cannot look one up.
 *
 * This endpoint has no username. The request carries a key and nothing else, so
 * the lookup must be "hash it, find the matching row" — which requires the hash
 * to be deterministic. A random salt would make that impossible.
 *
 * That is safe here only because these keys are not passwords. generateApiKey()
 * produces 256 bits from the OS CSPRNG; there is no dictionary to try and
 * brute force is not a meaningful threat, so a slow hash would buy nothing.
 *
 * The whole argument depends on keys being generated by generateApiKey() or
 * issue_api_key() in SQL. A hand-picked key like "test123" would be trivially
 * brute-forceable against this hash — never create one that way.
 */
export function hashApiKey(rawKey: string): string {
  return createHash("sha256").update(rawKey, "utf8").digest("hex");
}

/**
 * Mint a new API key. Returns the raw value and its hash.
 *
 * Store `hash`. Show `raw` to the operator once, then discard it — recovering
 * it later is exactly what hashing is meant to prevent.
 *
 * randomBytes() is the OS cryptographically secure generator. Math.random() is
 * not, and would be a serious vulnerability here: its output is predictable
 * from previous values, so an attacker who saw one key could derive others.
 */
export function generateApiKey(): { raw: string; hash: string } {
  const raw = API_KEY_PREFIX + randomBytes(KEY_BYTES).toString("base64url");
  return { raw, hash: hashApiKey(raw) };
}

/**
 * Pull the raw key out of an `Authorization: Bearer <key>` header.
 * Returns null when the header is missing or not a well-formed bearer token.
 */
export function extractBearerToken(header: string | null): string | null {
  if (!header) return null;

  const match = /^Bearer\s+(.+)$/i.exec(header.trim());
  if (!match) return null;

  const token = match[1].trim();
  return token.length > 0 ? token : null;
}

/**
 * Constant-time string comparison.
 *
 * Not used on the main lookup path — that is an indexed database equality on a
 * hash, where there is no useful timing signal to leak. Exported for future
 * code that needs to compare a secret it already holds, such as verifying the
 * n8n shared webhook secret.
 *
 * A plain `===` on secrets returns faster the earlier it finds a mismatched
 * character. Given enough samples that timing difference reveals the secret one
 * character at a time. timingSafeEqual always inspects every byte.
 */
export function safeCompare(a: string, b: string): boolean {
  const bufA = Buffer.from(a, "utf8");
  const bufB = Buffer.from(b, "utf8");
  // Length itself is not secret, and timingSafeEqual throws on a mismatch.
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}
