-- =============================================================================
-- ZELLÉ Lead OS — 001: Core schema
-- =============================================================================
-- Tenancy model: every business is an `organization`. Every row that belongs to
-- a tenant carries an `organization_id`. Row Level Security (migration 003) is
-- what actually enforces isolation; this file only builds the shapes.
--
-- Conventions used here and explained in supabase/README.md:
--   * uuid primary keys generated by gen_random_uuid() (built into Postgres 13+)
--   * timestamptz everywhere, never `timestamp`
--   * text + CHECK constraint instead of Postgres ENUM types
--   * every foreign key column gets an index (Postgres does NOT create these)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Shared trigger: keep updated_at honest
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'BEFORE UPDATE trigger. Stamps updated_at server-side so a client cannot lie about it.';


-- -----------------------------------------------------------------------------
-- organizations — the tenant root
-- -----------------------------------------------------------------------------
create table public.organizations (
  id          uuid        primary key default gen_random_uuid(),
  name        text        not null check (length(trim(name)) between 1 and 200),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger organizations_set_updated_at
  before update on public.organizations
  for each row execute function public.set_updated_at();

comment on table public.organizations is
  'Tenant root. One row per business using ZELLÉ. All isolation is keyed off this id.';


-- -----------------------------------------------------------------------------
-- users — application profile, 1:1 with auth.users
-- -----------------------------------------------------------------------------
-- `id` is the SAME uuid as auth.users.id. Supabase owns the `auth` schema
-- (passwords, sessions, providers); we never write to it directly. This table is
-- the application-side half: which org you belong to, your role, your name.
--
-- organization_id is NULLABLE on purpose. A brand-new signup with no invitation
-- lands here with organization_id = NULL, and because RLS compares
-- `organization_id = current_org_id()` — and `NULL = NULL` is NULL, not true —
-- such a user can see exactly nothing. Unassigned defaults to locked out.
-- -----------------------------------------------------------------------------
create table public.users (
  id               uuid        primary key references auth.users (id) on delete cascade,
  organization_id  uuid        references public.organizations (id) on delete cascade,
  name             text,
  email            text,
  role             text        not null default 'staff' check (role in ('admin', 'staff')),
  is_active        boolean     not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  -- Target for the composite foreign keys below. This is the trick that makes
  -- "an activity's actor must be in the same org as the activity" a database
  -- guarantee rather than something the app has to remember.
  constraint users_id_org_key unique (id, organization_id)
);

create index users_organization_id_idx on public.users (organization_id);
create index users_email_idx            on public.users (lower(email));

create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

comment on table public.users is
  'Application profile for an authenticated person. id mirrors auth.users.id. '
  'organization_id NULL = provisioned but not yet assigned to a tenant; sees nothing under RLS.';


-- -----------------------------------------------------------------------------
-- invitations — how organization_id and role get assigned at signup, safely
-- -----------------------------------------------------------------------------
-- Requirement: "organization_id and role assignable by an admin during signup."
--
-- The tempting shortcut is to read them from the signup payload
-- (auth.users.raw_user_meta_data). Do not: that field is written by whoever
-- calls signUp() from the browser, so anyone could self-assign
-- {"organization_id": "<someone else's org>", "role": "admin"}. It is user
-- input, not a trusted claim.
--
-- Instead an admin pre-creates an invitation row. RLS (migration 003) only lets
-- an admin insert one for their OWN org, so the org/role pair is trustworthy by
-- the time the signup trigger reads it back.
-- -----------------------------------------------------------------------------
create table public.invitations (
  id               uuid        primary key default gen_random_uuid(),
  organization_id  uuid        not null references public.organizations (id) on delete cascade,
  email            text        not null check (position('@' in email) > 1),
  role             text        not null default 'staff' check (role in ('admin', 'staff')),
  invited_by       uuid        references public.users (id) on delete set null,
  expires_at       timestamptz not null default now() + interval '14 days',
  accepted_at      timestamptz,
  accepted_by      uuid        references public.users (id) on delete set null,
  created_at       timestamptz not null default now()
);

-- At most one *pending* invitation per email per org. Partial unique index:
-- the constraint only applies to rows matching the WHERE clause, so a second
-- invite is allowed once the first has been accepted.
create unique index invitations_pending_unique_idx
  on public.invitations (organization_id, lower(email))
  where accepted_at is null;

create index invitations_email_idx           on public.invitations (lower(email)) where accepted_at is null;
create index invitations_organization_id_idx on public.invitations (organization_id);

comment on table public.invitations is
  'Admin-created, server-trusted assignment of organization_id + role for a not-yet-existing user. '
  'Consumed by public.handle_new_user() on signup.';


-- -----------------------------------------------------------------------------
-- leads
-- -----------------------------------------------------------------------------
create table public.leads (
  id                  uuid        primary key default gen_random_uuid(),
  organization_id     uuid        not null references public.organizations (id) on delete cascade,
  assigned_to         uuid,
  name                text,
  phone               text,
  channel             text        not null check (channel in ('instagram', 'facebook', 'whatsapp')),
  source              text,
  ai_score            integer     check (ai_score between 0 and 100),
  ai_summary          text,
  status              text        not null default 'New' check (length(trim(status)) between 1 and 100),
  qualification_data  jsonb       not null default '{}'::jsonb
                                  check (jsonb_typeof(qualification_data) = 'object'),
  source_message_id   text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  -- Composite FK: the assignee must exist AND be in this lead's organization.
  -- ON DELETE SET NULL (assigned_to) names the single column to null out —
  -- without the column list Postgres would try to null organization_id too and
  -- fail against its NOT NULL. (Requires Postgres 15+; Supabase ships 15/17.)
  constraint leads_assigned_to_fkey
    foreign key (assigned_to, organization_id)
    references public.users (id, organization_id)
    on delete set null (assigned_to),

  -- Target for conversations/activities composite FKs.
  constraint leads_id_org_key unique (id, organization_id)
);

-- Idempotency for the n8n/ManyChat webhook: replaying the same inbound message
-- must not create a second lead. Scoped to the org rather than global — see
-- README, "Why source_message_id is unique per org".
-- NULLs are exempt (Postgres treats NULLs as distinct), so manually created
-- leads with no source_message_id are unaffected.
create unique index leads_org_source_message_id_key
  on public.leads (organization_id, source_message_id)
  where source_message_id is not null;

create index leads_organization_id_idx  on public.leads (organization_id);
create index leads_org_created_at_idx   on public.leads (organization_id, created_at desc);
create index leads_org_status_idx       on public.leads (organization_id, status);
create index leads_assigned_to_idx      on public.leads (assigned_to) where assigned_to is not null;
create index leads_qualification_gin    on public.leads using gin (qualification_data);

create trigger leads_set_updated_at
  before update on public.leads
  for each row execute function public.set_updated_at();

comment on column public.leads.source_message_id is
  'Upstream platform message id. Unique per organization — the idempotency key for webhook ingestion.';
comment on column public.leads.status is
  'Free text, expected to match a pipeline_stages.name for this org. Deliberately not a FK so renaming '
  'or deleting a stage cannot orphan leads; reconcile in the application layer.';


-- -----------------------------------------------------------------------------
-- conversations
-- -----------------------------------------------------------------------------
-- NOTE — deliberate addition: the spec gave conversations only a lead_id.
-- Conversations hold the actual chat transcripts, so they need tenant isolation
-- as much as leads do, and RLS needs an organization_id on the row to filter on
-- without an expensive join. The composite FK below makes the denormalized
-- organization_id provably equal to the parent lead's — it cannot drift.
-- -----------------------------------------------------------------------------
create table public.conversations (
  id               uuid        primary key default gen_random_uuid(),
  organization_id  uuid        not null,
  lead_id          uuid        not null,
  messages         jsonb       not null default '[]'::jsonb
                               check (jsonb_typeof(messages) = 'array'),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  constraint conversations_lead_fkey
    foreign key (lead_id, organization_id)
    references public.leads (id, organization_id)
    on delete cascade
);

create index conversations_lead_id_idx         on public.conversations (lead_id);
create index conversations_organization_id_idx on public.conversations (organization_id);

create trigger conversations_set_updated_at
  before update on public.conversations
  for each row execute function public.set_updated_at();

comment on column public.conversations.organization_id is
  'Denormalized from leads. Kept truthful by the composite FK, not by application code.';


-- -----------------------------------------------------------------------------
-- activities — append-only audit trail
-- -----------------------------------------------------------------------------
create table public.activities (
  id               uuid        primary key default gen_random_uuid(),
  organization_id  uuid        not null,
  lead_id          uuid        not null,
  actor_type       text        not null check (actor_type in ('ai', 'user', 'system')),
  actor_id         uuid,
  type             text        not null check (
                     type in ('status_change', 'note', 'assignment', 'call_logged', 'follow_up_set')
                   ),
  content          jsonb       not null default '{}'::jsonb
                               check (jsonb_typeof(content) = 'object'),
  created_at       timestamptz not null default now(),

  -- 'ai' and 'system' events must have no actor. A 'user' event normally has
  -- one, but is allowed NULL so that deleting an employee can null the actor_id
  -- (see the ON DELETE SET NULL below) without violating this constraint and
  -- making the user undeletable. actor_id = NULL with actor_type = 'user' reads
  -- as "a person did this, but that account no longer exists" — the correct
  -- tombstone for an audit trail. Insertion always supplies it: the RLS policy
  -- in migration 003 requires actor_id = auth.uid().
  constraint activities_actor_id_matches_type check (
    actor_type = 'user' or actor_id is null
  ),

  constraint activities_lead_fkey
    foreign key (lead_id, organization_id)
    references public.leads (id, organization_id)
    on delete cascade,

  -- Composite FK with a nullable column: Postgres skips the check entirely when
  -- any column of the key is NULL, so ai/system rows are fine, and human rows
  -- are forced to reference a user inside this same org.
  constraint activities_actor_fkey
    foreign key (actor_id, organization_id)
    references public.users (id, organization_id)
    on delete set null (actor_id)
);

create index activities_lead_created_at_idx  on public.activities (lead_id, created_at desc);
create index activities_organization_id_idx  on public.activities (organization_id);
create index activities_actor_id_idx         on public.activities (actor_id) where actor_id is not null;

comment on table public.activities is
  'Append-only audit trail. RLS grants no UPDATE or DELETE to end users (migration 003).';


-- -----------------------------------------------------------------------------
-- pipeline_stages — per-org configurable board columns
-- -----------------------------------------------------------------------------
create table public.pipeline_stages (
  id               uuid        primary key default gen_random_uuid(),
  organization_id  uuid        not null references public.organizations (id) on delete cascade,
  name             text        not null check (length(trim(name)) between 1 and 100),
  order_index      integer     not null default 0,
  created_at       timestamptz not null default now(),

  constraint pipeline_stages_org_name_key unique (organization_id, name)
);

-- order_index is intentionally NOT unique: a drag-and-drop reorder writes
-- several rows in one transaction and would trip a non-deferrable unique
-- constraint mid-update.
create index pipeline_stages_org_order_idx on public.pipeline_stages (organization_id, order_index);


-- -----------------------------------------------------------------------------
-- qualification_field_defs — per-org schema for leads.qualification_data
-- -----------------------------------------------------------------------------
create table public.qualification_field_defs (
  id               uuid        primary key default gen_random_uuid(),
  organization_id  uuid        not null references public.organizations (id) on delete cascade,
  field_key        text        not null check (field_key ~ '^[a-z][a-z0-9_]{0,62}$'),
  label            text        not null check (length(trim(label)) between 1 and 200),
  order_index      integer     not null default 0,
  created_at       timestamptz not null default now(),

  constraint qualification_field_defs_org_key_key unique (organization_id, field_key)
);

create index qualification_field_defs_org_order_idx
  on public.qualification_field_defs (organization_id, order_index);

comment on column public.qualification_field_defs.field_key is
  'Matches a top-level key inside leads.qualification_data. Restricted to snake_case so the '
  'jsonb keys stay predictable for the n8n/ManyChat payloads.';
